domain_path: C:\Users\belal\Basys3_Test\Vitis_WS\platform\export\platform\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
